### ISSUE TITLE
sbt Support?

### ISSUE THREAD

**Issue by vpong** [sameersingh/scalaplot#4]
Hey,

This isn't an issue, but I didn't know where else to post this. Do you plan on supporting sbt? Or do you know how to install this through sbt? This looks really nice and I'd like to try it out, but I'd rather not use Maven.

Thanks!

**Comment by sameersingh** [comment]
Thanks for the PR. I think I'm happy with Maven for now, but will probably move to sbt when I can figure out what the correct `build.sbt` for hosting on Maven Central looks like.

**Comment by sameersingh** [comment]
Closed using #8 from @nightscape
