### ISSUE TITLE
error: not found: value plot 

### ISSUE THREAD

**Issue by ehsanmok** [sameersingh/scalaplot#7]
When I run the first example, 

import org.sameersingh.scalaplot.Implicits._

val x = 0.0 until 2.0 * math.Pi by 0.1
output(PNG("docs/img/", "test"), plot(x ->(math.sin(_), math.cos(_))))

scala cannot find the plot function.

**Comment by sameersingh** [comment]
Did you include the implicits import (import
org.sameersingh.scalaplot.Implicits._)?

The example is also checked in as a test, which passes:
https://github.com/sameersingh/scalaplot/blob/master/src/test/scala/org/sameersingh/scalaplot/ExampleXYTest.scala#L142

**Comment by ehsanmok** [comment]
Yes, I did.

**Comment by sameersingh** [comment]
Ah sorry, it should be `xyChart` instead of `plot`. I should update the
README.
